name: Demo
on: workflow_dispatch # Workflow simple de GAction. Allows manual triggering of the workflow
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Step
        run: |
         echo "Hello World 1!"
         echo "Hello World 2!"